---
- name: essential
  hosts: all
  become: true
  tasks:
    - import_tasks: tasks/update.yaml
    - import_tasks: tasks/docker.yaml

- name: k3s(master)
  hosts: master
  tasks:
    - name: install k3s on master node
      shell: |
         curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s
      become: true

    - name: copying node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      become: true
    
    - name: output
      debug:
        msg: "{{ k3s_token.stdout }}"

- name: k3s(worker)
  hosts: worker
  vars_files:
    - vars.yaml
  tasks:
    - name: joining and installing
      shell: |
          curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['51.120.118.95'].ansible_host }}:6443 K3S_TOKEN={{ hostvars['51.120.118.95'].k3s_token.stdout }} sh - 
      become: true
    


    
